name: publish jar
on: workflow_dispatch
jobs: 
  build-uber-jar: 
    runs-on: ubuntu-latest
    steps:
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156
      - uses: actions/checkout@v3
      - name: create uber-jar
        run: bb -m main --help
